version: '3'
services:
  ads:
    build: ads
    ports:
      - "5000:5000"
    volumes:
      - ./ads:/app/main
    environment:
      - FLASK_APP=main.py
  redis:
    image: "redis:alpine"

networks:
        internalNetwork:
                external: false